// filter categories
const categories = [
    {
      name: 'Latest',
      filter: 'Latest',
    },
    {
      name: 'China',
      filter: 'China',
    },
    {
      name: 'Japan',
      filter: 'Japan',
    },
    {
      name: 'Korea',
      filter: 'Korea',
    },
    {
      name: 'Norway',
      filter: 'Norway',
    },
    {
      name: 'Sweden',
      filter: 'Sweden',
    },
    {
      name: 'Taiwan',
      filter: 'Taiwan',
    },
    {
      name: 'All',
      filter: 'all',
    },
  ];
  
  const images = [
    {
      id: '1',
      url: 'Japan (1).jpg',
      category: 'Japan',
      title: 'Japan (1)',
      },
      {
      id: '2',
      url: 'Japan (2).jpg',
      category: 'Japan',
      title: 'Japan (2)',
      },
      {
      id: '3',
      url: 'Japan (3).jpg',
      category: 'Japan',
      title: 'Japan (3)',
      },
      {
      id: '4',
      url: 'Japan (4).jpg',
      category: 'Japan',
      title: 'Japan (4)',
      },
      {
      id: '5',
      url: 'Japan (5).jpg',
      category: 'Japan',
      title: 'Japan (5)',
      },
      {
      id: '6',
      url: 'Japan (6).jpg',
      category: 'Japan',
      title: 'Japan (6)',
      },
      {
      id: '7',
      url: 'Japan (7).jpg',
      category: 'Japan',
      title: 'Japan (7)',
      },
      {
      id: '8',
      url: 'Japan (8).jpg',
      category: 'Japan',
      title: 'Japan (8)',
      },
      {
      id: '9',
      url: 'Japan (9).jpg',
      category: 'Japan',
      title: 'Japan (9)',
      },
      {
      id: '10',
      url: 'Japan (10).jpg',
      category: 'Japan',
      title: 'Japan (10)',
      },
      {
      id: '11',
      url: 'Japan (11).jpg',
      category: 'Japan',
      title: 'Japan (11)',
      },
      {
      id: '12',
      url: 'Japan (12).jpg',
      category: 'Japan',
      title: 'Japan (12)',
      },
      {
      id: '13',
      url: 'Japan (13).jpg',
      category: 'Japan',
      title: 'Japan (13)',
      },
      {
      id: '14',
      url: 'Japan (14).jpg',
      category: 'Japan',
      title: 'Japan (14)',
      },
      {
      id: '15',
      url: 'Japan (15).jpg',
      category: 'Japan',
      title: 'Japan (15)',
      },
      {
      id: '16',
      url: 'Japan (16).jpg',
      category: 'Japan',
      title: 'Japan (16)',
      },
      {
      id: '17',
      url: 'Japan (17).jpg',
      category: 'Japan',
      title: 'Japan (17)',
      },
      {
      id: '18',
      url: 'Japan (18).jpg',
      category: 'Japan',
      title: 'Japan (18)',
      },
      {
      id: '19',
      url: 'Japan (19).jpg',
      category: 'Japan',
      title: 'Japan (19)',
      },
      {
      id: '20',
      url: 'Japan (20).jpg',
      category: 'Japan',
      title: 'Japan (20)',
      },
      {
      id: '21',
      url: 'Japan (21).jpg',
      category: 'Japan',
      title: 'Japan (21)',
      },
      {
      id: '22',
      url: 'Japan (22).jpg',
      category: 'Japan',
      title: 'Japan (22)',
      },
      {
      id: '23',
      url: 'Japan (23).jpg',
      category: 'Japan',
      title: 'Japan (23)',
      },
      {
      id: '24',
      url: 'Japan (24).jpg',
      category: 'Japan',
      title: 'Japan (24)',
      },
      {
      id: '25',
      url: 'Japan (25).jpg',
      category: 'Japan',
      title: 'Japan (25)',
      },
      {
      id: '26',
      url: 'Japan (26).jpg',
      category: 'Japan',
      title: 'Japan (26)',
      },
      {
      id: '27',
      url: 'Japan (27).jpg',
      category: 'Japan',
      title: 'Japan (27)',
      },
      {
      id: '28',
      url: 'Japan (28).jpg',
      category: 'Japan',
      title: 'Japan (28)',
      },
      
        {
        id: '1',
        url: 'Korea (1).jpg',
        category: 'Korea',
        title: 'Korea (1)',
        },
        {
        id: '2',
        url: 'Korea (2).jpg',
        category: 'Korea',
        title: 'Korea (2)',
        },
        {
        id: '3',
        url: 'Korea (3).jpg',
        category: 'Korea',
        title: 'Korea (3)',
        },
        {
        id: '4',
        url: 'Korea (4).jpg',
        category: 'Korea',
        title: 'Korea (4)',
        },
        {
        id: '5',
        url: 'Korea (5).jpg',
        category: 'Korea',
        title: 'Korea (5)',
        },
        {
        id: '6',
        url: 'Korea (6).jpg',
        category: 'Korea',
        title: 'Korea (6)',
        },
        {
        id: '7',
        url: 'Korea (7).jpg',
        category: 'Korea',
        title: 'Korea (7)',
        },
        {
        id: '8',
        url: 'Korea (8).jpg',
        category: 'Korea',
        title: 'Korea (8)',
        },
        {
        id: '9',
        url: 'Korea (9).jpg',
        category: 'Korea',
        title: 'Korea (9)',
        },
        {
        id: '10',
        url: 'Korea (10).jpg',
        category: 'Korea',
        title: 'Korea (10)',
        },
        {
        id: '11',
        url: 'Korea (11).jpg',
        category: 'Korea',
        title: 'Korea (11)',
        },
        {
          id: '12',
          url: 'Korea (12).jpg',
          category: 'Korea',
          title: 'Korea (12)',
          },
        
        {
          id: '1',
          url: 'Norway (1).jpg',
          category: 'Norway',
          title: 'Norway (1)',
          },
          {
          id: '2',
          url: 'Norway (2).jpg',
          category: 'Norway',
          title: 'Norway (2)',
          },
          {
          id: '3',
          url: 'Norway (3).jpg',
          category: 'Norway',
          title: 'Norway (3)',
          },
          {
          id: '4',
          url: 'Norway (4).jpg',
          category: 'Norway',
          title: 'Norway (4)',
          },
          {
          id: '5',
          url: 'Norway (5).jpg',
          category: 'Norway',
          title: 'Norway (5)',
          },
          {
          id: '6',
          url: 'Norway (6).jpg',
          category: 'Norway',
          title: 'Norway (6)',
          },
          {
          id: '7',
          url: 'Norway (7).jpg',
          category: 'Norway',
          title: 'Norway (7)',
          },
          {
          id: '8',
          url: 'Norway (8).jpg',
          category: 'Norway',
          title: 'Norway (8)',
          },
          
          {
            id: '1',
            url: 'Sweden (1).jpg',
            category: 'Sweden',
            title: 'Sweden (1)',
            },
            {
            id: '2',
            url: 'Sweden (2).jpg',
            category: 'Sweden',
            title: 'Sweden (2)',
            },
            {
            id: '3',
            url: 'Sweden (3).jpg',
            category: 'Sweden',
            title: 'Sweden (3)',
            },
            {
            id: '4',
            url: 'Sweden (4).jpg',
            category: 'Sweden',
            title: 'Sweden (4)',
            },
            {
            id: '5',
            url: 'Sweden (5).jpg',
            category: 'Sweden',
            title: 'Sweden (5)',
            },
            {
            id: '6',
            url: 'Sweden (6).jpg',
            category: 'Sweden',
            title: 'Sweden (6)',
            },
            {
            id: '7',
            url: 'Sweden (7).jpg',
            category: 'Sweden',
            title: 'Sweden (7)',
            },
            {
            id: '8',
            url: 'Sweden (8).jpg',
            category: 'Sweden',
            title: 'Sweden (8)',
            },
            
            {
              id: '1',
              url: 'Taiwan (1).jpg',
              category: 'Taiwan',
              title: 'Taiwan (1)',
              },
              {
              id: '2',
              url: 'Taiwan (2).jpg',
              category: 'Taiwan',
              title: 'Taiwan (2)',
              },
              {
              id: '3',
              url: 'Taiwan (3).jpg',
              category: 'Taiwan',
              title: 'Taiwan (3)',
              },
              {
              id: '4',
              url: 'Taiwan (4).jpg',
              category: 'Taiwan',
              title: 'Taiwan (4)',
              },
              {
              id: '5',
              url: 'Taiwan (5).jpg',
              category: 'Taiwan',
              title: 'Taiwan (5)',
              },
              {
              id: '6',
              url: 'Taiwan (6).jpg',
              category: 'Taiwan',
              title: 'Taiwan (6)',
              },
              {
              id: '7',
              url: 'Taiwan (7).jpg',
              category: 'Taiwan',
              title: 'Taiwan (7)',
              },
              {
              id: '8',
              url: 'Taiwan (8).jpg',
              category: 'Taiwan',
              title: 'Taiwan (8)',
              },
              {
              id: '9',
              url: 'Taiwan (9).jpg',
              category: 'Taiwan',
              title: 'Taiwan (9)',
              },
              {
              id: '10',
              url: 'Taiwan (10).jpg',
              category: 'Taiwan',
              title: 'Taiwan (10)',
              },
              {
                id: '11',
                url: 'Taiwan (11).jpg',
                category: 'Taiwan',
                title: 'Taiwan (11)',
                },
                {
                id: '12',
                url: 'Taiwan (12).jpg',
                category: 'Taiwan',
                title: 'Taiwan (12)',
                },
                {
                  id: '13',
                  url: 'Taiwan (13).jpg',
                  category: 'Taiwan',
                  title: 'Taiwan (13)',
                  },
                  

            {
              id: '1',
              url: 'Latest (1).jpg',
              category: 'Latest',
              title: 'Latest (1)',
              },
              {
              id: '2',
              url: 'Latest (2).jpg',
              category: 'Latest',
              title: 'Latest (2)',
              },
              {
              id: '3',
              url: 'Latest (3).jpg',
              category: 'Latest',
              title: 'Latest (3)',
              },
              {
              id: '4',
              url: 'Latest (4).jpg',
              category: 'Latest',
              title: 'Latest (4)',
              },
              {
              id: '5',
              url: 'Latest (5).jpg',
              category: 'Latest',
              title: 'Latest (5)',
              },
              {
              id: '6',
              url: 'Latest (6).jpg',
              category: 'Latest',
              title: 'Latest (6)',
              },
              {
              id: '7',
              url: 'Latest (7).jpg',
              category: 'Latest',
              title: 'Latest (7)',
              },
              {
              id: '8',
              url: 'Latest (8).jpg',
              category: 'Latest',
              title: 'Latest (8)',
              },
              {
              id: '9',
              url: 'Latest (9).jpg',
              category: 'Latest',
              title: 'Latest (9)',
              },
              {
              id: '10',
              url: 'Latest (10).jpg',
              category: 'Latest',
              title: 'Latest (10)',
              },
              {
              id: '11',
              url: 'Latest (11).jpg',
              category: 'Latest',
              title: 'Latest (11)',
              },
              {
              id: '12',
              url: 'Latest (12).jpg',
              category: 'Latest',
              title: 'Latest (12)',
              },
              {
              id: '13',
              url: 'Latest (13).jpg',
              category: 'Latest',
              title: 'Latest (13)',
              },
              {
              id: '14',
              url: 'Latest (14).jpg',
              category: 'Latest',
              title: 'Latest (14)',
              },
              {
                id: '1',
                url: 'China (1).jpg',
                category: 'China',
                title: 'China (1)',
                },
                {
                id: '2',
                url: 'China (2).jpg',
                category: 'China',
                title: 'China (2)',
                },
                {
                id: '3',
                url: 'China (3).jpg',
                category: 'China',
                title: 'China (3)',
                },
                {
                id: '4',
                url: 'China (4).jpg',
                category: 'China',
                title: 'China (4)',
                },
                {
                id: '5',
                url: 'China (5).jpg',
                category: 'China',
                title: 'China (5)',
                },
                {
                id: '6',
                url: 'China (6).jpg',
                category: 'China',
                title: 'China (6)',
                },
                {
                id: '7',
                url: 'China (7).jpg',
                category: 'China',
                title: 'China (7)',
                },
                {
                id: '8',
                url: 'China (8).jpg',
                category: 'China',
                title: 'China (8)',
                },

              

                  
  ];
  